### ISSUE TITLE
Error while merging overlapping S2 images

### ISSUE THREAD

**Issue by VINCENTAFERRER** [kvos/CoastSat#165]
Hello Vos
     I encounter a error while downloading S2 images for the AOI of my study area. It tells that the S2 images couldnt be merged and advised me to raise an issue. The details are provided as screenshot. Please suggest on how to proceed. thanks in advance...

Vincent A Ferrer

![image](https://user-images.githubusercontent.com/76463942/102849338-f2f80880-443c-11eb-8551-6cac54635fec.png)

**Comment by kvos** [comment]
thanks for posting this Vincent, will check what is going on (we're in lockdown in Sydney so plenty of time to do this!). In the meanwhile you can go in SDS_download.py and comment lines 280 to 286, then it will not merge the S2 images and you can continue processing at that site.

**Comment by kvos** [comment]
can you post the script as .txt file so I can copy it across?

**Comment by VINCENTAFERRER** [comment]
Dear Vos
Apologies on reopening this post....
Hope you will be kind enough to look into this issue....
As suggested, I have attached herewith the script as text file...
[S2_MSI_merge_error.txt](https://github.com/kvos/CoastSat/files/6146039/S2_MSI_merge_error.txt)

**Comment by kvos** [comment]
hi vincent, I did find the bug and fixed it, you can just download the latest version of SDS_download.py and overwrite the old one in your coastsat folder and it should work.
There were quadruplicates (4 S2 images taken within 5 minutes) over your polygon, I suggest making the polygon smaller, split it in two or three and processing will be way more efficient
![image](https://user-images.githubusercontent.com/7217258/111399341-4f578500-8719-11eb-91b1-36f5cf56b740.png)

**Comment by VINCENTAFERRER** [comment]
Dear Vos
     thanks a lot for the updates... Yet I still face the same issue as seen in the attached file.... It is to be noted I dont get the error message as in the earlier case.
the issue persists in datasets downloaded since 2015 upto 23-10-2018. Please check...

![2015-11-28-05-15-10_S2](https://user-images.githubusercontent.com/76463942/111440039-f513ef80-872b-11eb-8fa0-f1e83df2b293.jpg)

**Comment by kvos** [comment]
must be some problem with the merging of the overlapping S2 images. Did you try making the polygon smaller to see if the issue persists?

**Comment by VINCENTAFERRER** [comment]
The issue still persists and also the error message displays even after reducing the area.... Though the earlier issue got solved...
the script for the same is also attached herewith as text....
![2018-12-07-05-15-22_S2](https://user-images.githubusercontent.com/76463942/111609399-4097cd80-8800-11eb-9edb-3fe1214d00b1.jpg)
 
[S2_MSI_merge_error_18-03-2021.txt](https://github.com/kvos/CoastSat/files/6162513/S2_MSI_merge_error_18-03-2021.txt)


![2018-12-07-05-15-25_S2](https://user-images.githubusercontent.com/76463942/111609366-3970bf80-8800-11eb-9422-e6439ac33706.jpg)

**Comment by kvos** [comment]
hey vincent, just checked again for that black section of the image, there is nothing wrong with the code, the issue is that we are missing one image. As you can see in the screenshot below, coastsat is downloading 3 images with the exact same timestamp but there should be a fourth one (I know why it's not downloading it and I may fix this next week if I have time). Basically your site is at the boundary between 4 tiles and each of them overlap slightly (the worst case scenario but we knew it was possible, just couldn't account for it until someone reported such a site).
![image](https://user-images.githubusercontent.com/7217258/111706325-33c5b900-8896-11eb-96d6-d586961ef74a.png)

I tested your second polygon on a small subset (2018-07-01 to 2018-10-01) and didn't run into any error. Will try with a longer sequence see if I can reproduce it

**Comment by kvos** [comment]
@VINCENTAFERRER  I made some further updates to SDS_download.py (see the latest commit above) and it now works with the smaller polygon as well. It's in the `development branch` if you could please test it that would be great. If it works fine I will push to the `master`.

**Comment by VINCENTAFERRER** [comment]
congrats and I think we have cracked it out....
I have used the pack from the development branch and found the images getting downloaded successfully...
I feel now it is good to go with the master and test it again...
Here is snap of the downloaded image for the same date as you had shown above...
![2018-08-09-05-14-28_S2](https://user-images.githubusercontent.com/76463942/111742122-98d8d900-88ad-11eb-8988-1bfddcef15f1.jpg)

**Comment by VINCENTAFERRER** [comment]
I hope the updated SDS_download.py from the development branch is pushed to the master.
I plan to test it once again...

**Comment by kvos** [comment]
I haven't pushed it yet as I need to check that these updates that work at your site do not create new bugs at other "tricky" sites where there are several overlapping S2 tiles.

**Comment by VINCENTAFERRER** [comment]
Sure and thats good idea.....please update on the progress...

**Comment by kvos** [comment]
the development branch has been merged into the master and I also released a new version CoastSat v1.1.1
feel free to reopen this issue if a new problem pops up, will close it for now

**Comment by VINCENTAFERRER** [comment]
Thanks for the updates....Will look into the things and respond back on any newly arising issue....
regards
VincentCGL, NCESS.
    On Thursday, 1 April, 2021, 06:11:56 am IST, Kilian Vos ***@***.***> wrote:  
 
 


Closed #165.

**Comment by VINCENTAFERRER** [comment]
Dear Vos
     AS suggested earlier, I had downloaded the CoastSat v1.1.1 and on execution, I get the error message as shown in screenshot.
![image](https://user-images.githubusercontent.com/76463942/114869878-23f9b000-9e15-11eb-9475-6bb37bd6ecd5.png)
Yet when I recheck the images, there seem to be no issues as that arised earlier (still dont know why this message pops out).
But there is a new issue as shown down while generating the jpeg images as reading the metadata:
![image](https://user-images.githubusercontent.com/76463942/114870113-6c18d280-9e15-11eb-80b7-af06f7cadf29.png)
Though I couldnt exactly troubleshoot what would be the error, I just went through the command prompt window which suggested that one image corresponding to date (02-03-2017) was missing.
      Please provide suggestions on why the data didnt download though the metadata is populated with the details and if the error shown here is due to the same or something else....

I feel I confuse a little, but i hope you could understand the issue...

the details of the AOI are attached herewith...

Thanks in advance...
[error_15-04-2021.txt](https://github.com/kvos/CoastSat/files/6317949/error_15-04-2021.txt)
